steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/chisom-100845938/$REPO_NAME:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/chisom-100845938/$REPO_NAME:$COMMIT_SHA']
options:
  logging: 'CLOUD_LOGGING_ONLY'
  logStreamingOption: 'STREAM_ON'
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
