steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chisom-100845938:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chisom-100845938:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'chisom-100845938',
           '--image', 'gcr.io/$PROJECT_ID/chisom-100845938:$SHORT_SHA',
           '--region', 'us-central1',
           '--platform', 'managed']

